import { Router } from 'express';
import healthRouter from './health.routes';
import authRouter from './auth.routes';
import userRouter from './user.routes';
import adminRouter from './admin.routes';
import courseRouter from './course.routes';
import lessonRouter from './lesson.routes';
import problemRouter from './problem.routes';
import submissionRouter from './submission.routes';
import codeRouter from './code.routes';
import quizRouter from './quiz.routes';
import quizAttemptRouter from './quizAttempt.routes';
import projectRouter from './project.routes';
import tutorialRouter from './tutorial.routes';
import certificateRouter from './certificate.routes';
import achievementRouter from './achievement.routes';
import notificationRouter from './notification.routes';
import faqRouter from './faq.routes';
import testimonialRouter from './testimonial.routes';
import mentorRouter from './mentor.routes';
import paymentRouter from './payment.routes';
import careerRouter from './career.routes';
import settingsRouter from './settings.routes';
import monthlyContestRouter from './monthlyContest.routes';
import rewardRouter from './reward.routes';
import discussionRouter from './discussion.routes';
import necAiRouter from './necAi.routes';
import duelRouter from './duel.routes';
import problemListRouter from './problemList.routes';
import postRouter from './post.routes';
import footerRouter from './footer.routes';

const router = Router();


router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/admin', adminRouter);
router.use('/settings', settingsRouter);
router.use('/payments', paymentRouter);
router.use('/careers', careerRouter);
router.use('/courses', courseRouter);
router.use('/lessons', lessonRouter);
router.use('/problems', problemRouter);
router.use('/submissions', submissionRouter);
router.use('/code', codeRouter);
router.use('/quizzes', quizRouter);
router.use('/quiz-attempts', quizAttemptRouter);
router.use('/projects', projectRouter);
router.use('/tutorials', tutorialRouter);
router.use('/certificates', certificateRouter);
router.use('/achievements', achievementRouter);
router.use('/gamification', achievementRouter);
router.use('/notifications', notificationRouter);
router.use('/faqs', faqRouter);
router.use('/testimonials', testimonialRouter);
router.use('/mentors', mentorRouter);
router.use('/monthly-contest', monthlyContestRouter);
router.use('/rewards', rewardRouter);
router.use('/discussions', discussionRouter);
router.use('/nec-ai', necAiRouter);
router.use('/duels', duelRouter);
router.use('/problem-lists', problemListRouter);
router.use('/bookmarks', problemListRouter);
router.use('/posts', postRouter);
router.use('/footer', footerRouter);

export default router;
