import dotenv from 'dotenv';
import path from 'path';
import { connectDB, disconnectDB } from '../config/db';
import { TutorialSubject } from '../models/tutorialSubject.model';
import { Tutorial } from '../models/tutorial.model';
import { logger } from '../utils/logger';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

export interface ISubjectSeed {
  title: string;
  slug: string;
  shortTitle: string;
  category: string;
  iconName: string;
  description: string;
  lang: string;
  codeExt: string;
  sampleCode1: string;
  sampleCode2: string;
  ch2Title: string;
}

export const ALL_IT_SUBJECTS: ISubjectSeed[] = [
  // --- Web & Frontend ---
  {
    title: 'HTML',
    slug: 'html',
    shortTitle: 'HTML',
    category: 'Web Development',
    iconName: 'FileCode',
    description: 'Master HTML5 semantic document structure, accessibility (a11y), forms, canvas, and web performance.',
    lang: 'html',
    codeExt: 'index.html',
    sampleCode1: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Hello World</title>\n</head>\n<body>\n  <header><h1>Welcome to NextEra</h1></header>\n  <main><p>Modern semantic web development starts here.</p></main>\n</body>\n</html>`,
    sampleCode2: `<form action="/api/submit" method="POST">\n  <label for="username">Username:</label>\n  <input type="text" id="username" name="username" required>\n  <button type="submit">Register</button>\n</form>`,
    ch2Title: 'HTML5 Semantic Elements & Forms',
  },
  {
    title: 'CSS',
    slug: 'css',
    shortTitle: 'CSS',
    category: 'Web Development',
    iconName: 'Layers',
    description: 'Learn modern CSS3, Flexbox, CSS Grid layouts, custom properties, animations, and responsive mobile design.',
    lang: 'css',
    codeExt: 'style.css',
    sampleCode1: `:root {\n  --primary: #10b981;\n  --dark: #0f172a;\n}\n\nbody {\n  font-family: system-ui, sans-serif;\n  background: var(--dark);\n  color: #fff;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh;\n}`,
    sampleCode2: `.container {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n  gap: 1.5rem;\n  padding: 2rem;\n}`,
    ch2Title: 'CSS Flexbox & Responsive Grid Layouts',
  },
  {
    title: 'JavaScript',
    slug: 'javascript',
    shortTitle: 'JavaScript',
    category: 'Web Development',
    iconName: 'FileCode',
    description: 'Deep dive into modern ES2024 JavaScript, V8 Event Loop, closures, Promises, Async/Await, and DOM APIs.',
    lang: 'javascript',
    codeExt: 'app.js',
    sampleCode1: `// Modern ES6+ JavaScript Foundations\nconst greet = (name) => {\n  return \`Welcome to NextEra Coders, \${name}!\`;\n};\n\nconsole.log(greet('Developer'));`,
    sampleCode2: `async function fetchUserData(userId) {\n  try {\n    const res = await fetch(\`https://api.example.com/users/\${userId}\`);\n    const data = await res.json();\n    return data;\n  } catch (err) {\n    console.error('Fetch failed:', err);\n  }\n}`,
    ch2Title: 'JavaScript Event Loop & Asynchronous Promises',
  },
  {
    title: 'TypeScript',
    slug: 'typescript',
    shortTitle: 'TypeScript',
    category: 'Web Development',
    iconName: 'FileCode',
    description: 'Type safety, generics, utility types, interfaces, union types, and production TypeScript architecture.',
    lang: 'typescript',
    codeExt: 'types.ts',
    sampleCode1: `interface User {\n  id: string;\n  name: string;\n  role: 'admin' | 'student';\n}\n\nfunction printRole(user: User): string {\n  return \`\${user.name} is a \${user.role}\`;\n}`,
    sampleCode2: `type ApiResponse<T> = {\n  success: boolean;\n  data: T;\n  message?: string;\n};\n\nfunction processResult<T>(res: ApiResponse<T>): T {\n  return res.data;\n}`,
    ch2Title: 'TypeScript Generics & Advanced Utility Types',
  },
  {
    title: 'React',
    slug: 'react',
    shortTitle: 'React',
    category: 'Web Development',
    iconName: 'Layers',
    description: 'Master React 19 functional components, Hooks (useState, useEffect, useMemo), Context API, and Virtual DOM.',
    lang: 'javascript',
    codeExt: 'Component.jsx',
    sampleCode1: `import React, { useState } from 'react';\n\nexport function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(c => c + 1)}>\n      Count is: {count}\n    </button>\n  );\n}`,
    sampleCode2: `import { useEffect, useState } from 'react';\n\nexport function useOnlineStatus() {\n  const [isOnline, setIsOnline] = useState(navigator.onLine);\n  useEffect(() => {\n    const handleStatus = () => setIsOnline(navigator.onLine);\n    window.addEventListener('online', handleStatus);\n    window.addEventListener('offline', handleStatus);\n    return () => {\n      window.removeEventListener('online', handleStatus);\n      window.removeEventListener('offline', handleStatus);\n    };\n  }, []);\n  return isOnline;\n}`,
    ch2Title: 'React Hooks & Virtual DOM Reconciliation',
  },
  {
    title: 'Next.js',
    slug: 'nextjs',
    shortTitle: 'Next.js',
    category: 'Web Development',
    iconName: 'Layers',
    description: 'Server Components (RSC), App Router, Server Actions, SSR, SSG, incremental static regeneration (ISR).',
    lang: 'javascript',
    codeExt: 'page.jsx',
    sampleCode1: `// Next.js Server Component\nexport default async function Page() {\n  const data = await fetch('https://api.github.com/repos/vercel/next.js', { cache: 'no-store' });\n  const repo = await data.json();\n  return <div>Next.js Stars: {repo.stargazers_count}</div>;\n}`,
    sampleCode2: `export async function POST(req) {\n  const body = await req.json();\n  return Response.json({ message: 'Success', body });\n}`,
    ch2Title: 'Next.js App Router & React Server Components',
  },
  {
    title: 'Vue.js',
    slug: 'vue',
    shortTitle: 'Vue.js',
    category: 'Web Development',
    iconName: 'Layers',
    description: 'Vue 3 Composition API, reactive state (ref/reactive), Pinia state store, and single file components (SFC).',
    lang: 'javascript',
    codeExt: 'App.vue',
    sampleCode1: `<script setup>\nimport { ref } from 'vue';\nconst message = ref('Hello Vue 3!');\n</script>\n<template>\n  <h1>{{ message }}</h1>\n</template>`,
    sampleCode2: `import { defineStore } from 'pinia';\nexport const useCounterStore = defineStore('counter', {\n  state: () => ({ count: 0 }),\n  actions: { increment() { this.count++; } }\n});`,
    ch2Title: 'Vue 3 Composition API & Reactivity Engine',
  },
  {
    title: 'Angular',
    slug: 'angular',
    shortTitle: 'Angular',
    category: 'Web Development',
    iconName: 'Layers',
    description: 'Angular standalone components, Signals, RxJS Observables, Dependency Injection, and TypeScript architecture.',
    lang: 'typescript',
    codeExt: 'app.component.ts',
    sampleCode1: `import { Component, signal } from '@angular/core';\n\n@Component({\n  selector: 'app-root',\n  template: '<button (click)=\"increment()\">Count: {{ count() }}</button>',\n  standalone: true,\n})\nexport class AppComponent {\n  count = signal(0);\n  increment() { this.count.update(c => c + 1); }\n}`,
    sampleCode2: `import { Injectable } from '@angular/core';\n@Injectable({ providedIn: 'root' })\nexport class DataService {\n  getData() { return ['NextEra', 'Angular', 'Signals']; }\n}`,
    ch2Title: 'Angular Signals & Dependency Injection System',
  },
  {
    title: 'Tailwind CSS',
    slug: 'tailwind',
    shortTitle: 'Tailwind CSS',
    category: 'Web Development',
    iconName: 'Layers',
    description: 'Utility-first styling, responsive design breakpoints, dark mode variants, arbitrary values, and JIT compilation.',
    lang: 'html',
    codeExt: 'index.html',
    sampleCode1: `<div class="max-w-md mx-auto bg-white dark:bg-slate-900 rounded-2xl shadow-xl p-6 border border-slate-200 dark:border-slate-800">\n  <h2 class="text-xl font-bold text-slate-900 dark:text-white">Tailwind Card</h2>\n  <p class="text-sm text-slate-500 mt-2">Zero CSS written manually.</p>\n</div>`,
    sampleCode2: `<button class="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-medium transition-all shadow-md active:scale-95">\n  Click Me\n</button>`,
    ch2Title: 'Tailwind CSS Custom Design Systems & JIT Compiler',
  },
  {
    title: 'Bootstrap',
    slug: 'bootstrap',
    shortTitle: 'Bootstrap',
    category: 'Web Development',
    iconName: 'Layers',
    description: 'Bootstrap 5 12-column responsive layout grid, interactive modals, navbars, utility classes, and Sass variables.',
    lang: 'html',
    codeExt: 'index.html',
    sampleCode1: `<div class="container py-5">\n  <div class="row g-4">\n    <div class="col-md-6 col-lg-4">\n      <div class="card p-3 shadow-sm">Card Column 1</div>\n    </div>\n  </div>\n</div>`,
    sampleCode2: `<nav class="navbar navbar-expand-lg navbar-dark bg-dark">\n  <div class="container-fluid">\n    <a class="navbar-brand" href="#">NextEra</a>\n  </div>\n</nav>`,
    ch2Title: 'Bootstrap 5 Grid System & Responsive Breakpoints',
  },
  {
    title: 'Redux',
    slug: 'redux',
    shortTitle: 'Redux',
    category: 'Web Development',
    iconName: 'Layers',
    description: 'Predictable state container, Redux Toolkit (RTK), slices, createAsyncThunk, Immer immutability, and devtools.',
    lang: 'javascript',
    codeExt: 'store.js',
    sampleCode1: `import { createSlice, configureStore } from '@reduxjs/toolkit';\n\nconst counterSlice = createSlice({\n  name: 'counter',\n  initialState: { value: 0 },\n  reducers: {\n    increment: state => { state.value += 1; },\n  },\n});\n\nexport const { increment } = counterSlice.actions;\nexport const store = configureStore({ reducer: { counter: counterSlice.reducer } });`,
    sampleCode2: `import { createAsyncThunk } from '@reduxjs/toolkit';\nexport const fetchItems = createAsyncThunk('items/fetch', async () => {\n  const res = await fetch('/api/items');\n  return res.json();\n});`,
    ch2Title: 'Redux Toolkit (RTK) & Async Thunk Architecture',
  },
  {
    title: 'GraphQL',
    slug: 'graphql',
    shortTitle: 'GraphQL',
    category: 'Web Development',
    iconName: 'Network',
    description: 'Declarative queries, mutations, subscriptions, Apollo Client, schema definition language (SDL), and resolvers.',
    lang: 'javascript',
    codeExt: 'schema.graphql',
    sampleCode1: `type Query {\n  user(id: ID!): User\n  allTutorials: [Tutorial!]!\n}\n\ntype User {\n  id: ID!\n  name: String!\n  email: String!\n}`,
    sampleCode2: `const resolvers = {\n  Query: {\n    user: async (_, { id }) => await UserModel.findById(id),\n  },\n};`,
    ch2Title: 'GraphQL Resolvers, Schema Types & Mutations',
  },
  {
    title: 'REST APIs',
    slug: 'restapi',
    shortTitle: 'REST APIs',
    category: 'Web Development',
    iconName: 'Network',
    description: 'HTTP verbs (GET, POST, PUT, DELETE, PATCH), idempotency, status codes, query pagination, headers, and CORS.',
    lang: 'javascript',
    codeExt: 'routes.js',
    sampleCode1: `// REST API Controller Pattern\napp.get('/api/v1/tutorials', (req, res) => {\n  const page = parseInt(req.query.page) || 1;\n  res.status(200).json({ status: 'success', page, data: [] });\n});`,
    sampleCode2: `app.post('/api/v1/tutorials', (req, res) => {\n  const { title } = req.body;\n  if (!title) return res.status(400).json({ error: 'Title required' });\n  res.status(201).json({ status: 'created', id: 'tut_123' });\n});`,
    ch2Title: 'RESTful API Standards & Error Handling Best Practices',
  },
  {
    title: 'WebSockets',
    slug: 'websockets',
    shortTitle: 'WebSockets',
    category: 'Web Development',
    iconName: 'Network',
    description: 'Full-duplex bidirectional communication, Socket.io, handshake protocols, room broadcasts, and heartbeat pings.',
    lang: 'javascript',
    codeExt: 'server.js',
    sampleCode1: `const { Server } = require('socket.io');\nconst io = new Server(server, { cors: { origin: '*' } });\n\nio.on('connection', (socket) => {\n  console.log('Client connected:', socket.id);\n  socket.on('chatMessage', (msg) => io.emit('broadcast', msg));\n});`,
    sampleCode2: `const socket = io('http://localhost:5000');\nsocket.emit('joinRoom', { room: 'dev-lobby' });\nsocket.on('notification', data => console.log('Update:', data));`,
    ch2Title: 'WebSocket Protocols, Socket.IO & Real-Time Sync',
  },

  // --- Backend & Runtimes ---
  {
    title: 'Node.js',
    slug: 'nodejs',
    shortTitle: 'Node.js',
    category: 'Backend & Runtime',
    iconName: 'Terminal',
    description: 'Libuv asynchronous event loop, non-blocking I/O, Buffer, Stream pipelines, Cluster workers, and native modules.',
    lang: 'javascript',
    codeExt: 'index.js',
    sampleCode1: `const http = require('http');\n\nconst server = http.createServer((req, res) => {\n  res.writeHead(200, { 'Content-Type': 'application/json' });\n  res.end(JSON.stringify({ message: 'Hello from Node.js runtime!' }));\n});\n\nserver.listen(5000);`,
    sampleCode2: `const fs = require('fs');\nconst readStream = fs.createReadStream('large_data.csv');\nreadStream.on('data', chunk => console.log('Read chunk:', chunk.length));`,
    ch2Title: 'Node.js Event Loop, Worker Threads & Stream Pipelines',
  },
  {
    title: 'Express.js',
    slug: 'express',
    shortTitle: 'Express.js',
    category: 'Backend & Runtime',
    iconName: 'Terminal',
    description: 'Middleware chaining, Router modules, JSON payload parsers, error-handling middleware, and JWT authentication.',
    lang: 'javascript',
    codeExt: 'app.js',
    sampleCode1: `const express = require('express');\nconst app = express();\n\napp.use(express.json());\napp.get('/health', (req, res) => res.json({ status: 'ok', uptime: process.uptime() }));\n\napp.listen(5000);`,
    sampleCode2: `// Custom Auth Middleware\nconst authMiddleware = (req, res, next) => {\n  const token = req.headers.authorization;\n  if (!token) return res.status(401).json({ error: 'Unauthorized' });\n  next();\n};`,
    ch2Title: 'Express Middleware Lifecycle & Error Boundaries',
  },
  {
    title: 'Django',
    slug: 'django',
    shortTitle: 'Django',
    category: 'Backend & Runtime',
    iconName: 'FileCode2',
    description: 'Python web framework, Model-View-Template (MVT), Django ORM, authentication system, admin site, and REST framework.',
    lang: 'python',
    codeExt: 'views.py',
    sampleCode1: `from django.http import JsonResponse\n\ndef home(request):\n    return JsonResponse({"message": "Welcome to Django Backend"})\n`,
    sampleCode2: `from django.db import models\n\nclass Tutorial(models.Model):\n    title = models.CharField(max_length=200)\n    created_at = models.DateTimeField(auto_now_add=True)\n`,
    ch2Title: 'Django ORM Models & REST Framework (DRF)',
  },
  {
    title: 'FastAPI',
    slug: 'fastapi',
    shortTitle: 'FastAPI',
    category: 'Backend & Runtime',
    iconName: 'FileCode2',
    description: 'High-performance Python ASGI API framework, Pydantic type validation, Swagger documentation, and Async I/O.',
    lang: 'python',
    codeExt: 'main.py',
    sampleCode1: `from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/")\nasync def read_root():\n    return {"message": "High-performance FastAPI service"}\n`,
    sampleCode2: `from pydantic import BaseModel\n\nclass Item(BaseModel):\n    name: str\n    price: float\n\n@app.post("/items")\ndef create_item(item: Item):\n    return {"created": item.name}\n`,
    ch2Title: 'FastAPI Pydantic Validation & Async Endpoints',
  },
  {
    title: 'Spring Boot',
    slug: 'spring-boot',
    shortTitle: 'Spring Boot',
    category: 'Backend & Runtime',
    iconName: 'Coffee',
    description: 'Enterprise Java backend, Inversion of Control (IoC), Spring Data JPA, Hibernate ORM, and Microservices.',
    lang: 'java',
    codeExt: 'Application.java',
    sampleCode1: `package com.nextera;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class Application {\n    public static void main(String[] args) {\n        SpringApplication.run(Application.class, args);\n    }\n}`,
    sampleCode2: `import org.springframework.web.bind.annotation.*;\n\n@RestController\n@RequestMapping("/api")\npublic class ApiController {\n    @GetMapping("/hello")\n    public String hello() { return "Hello Spring Boot!"; }\n}`,
    ch2Title: 'Spring Boot REST Controllers & Spring Data JPA',
  },

  // --- Core Computer Science ---
  {
    title: 'DBMS',
    slug: 'dbms',
    shortTitle: 'DBMS',
    category: 'Core Computer Science',
    iconName: 'Database',
    description: 'Database Management Systems, Relational Algebra, ER Models, Normalization (1NF to BCNF), and ACID Transactions.',
    lang: 'sql',
    codeExt: 'queries.sql',
    sampleCode1: `-- Create Tables with Primary and Foreign Keys\nCREATE TABLE students (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(100) NOT NULL,\n  email VARCHAR(150) UNIQUE NOT NULL\n);`,
    sampleCode2: `-- Transaction with ACID Guarantee\nBEGIN TRANSACTION;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;`,
    ch2Title: 'Relational Model, Normalization & ACID Transactions',
  },
  {
    title: 'Operating Systems',
    slug: 'os',
    shortTitle: 'Operating Systems',
    category: 'Core Computer Science',
    iconName: 'Cpu',
    description: 'Process life cycles, CPU scheduling algorithms, Virtual Memory, Paging, Page replacement, and Deadlocks.',
    lang: 'c',
    codeExt: 'fork.c',
    sampleCode1: `#include <stdio.h>\n#include <unistd.h>\n\nint main() {\n    pid_t pid = fork();\n    if (pid == 0) {\n        printf("Child process running with PID: %d\\n", getpid());\n    } else {\n        printf("Parent process spawned child %d\\n", pid);\n    }\n    return 0;\n}`,
    sampleCode2: `// Deadlock Banker's Algorithm verification logic in C\n#define PROCESSES 5\n#define RESOURCES 3\nint allocation[PROCESSES][RESOURCES];\nint max_demand[PROCESSES][RESOURCES];`,
    ch2Title: 'Process Scheduling, Virtual Memory & Deadlocks',
  },
  {
    title: 'Computer Networks',
    slug: 'cn',
    shortTitle: 'Computer Networks',
    category: 'Core Computer Science',
    iconName: 'Network',
    description: 'OSI 7-layer model, TCP/IP stack, Socket programming, IP addressing, Subnetting, DNS, and TCP handshake.',
    lang: 'python',
    codeExt: 'tcp_client.py',
    sampleCode1: `import socket\n\nclient = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\nclient.connect(('localhost', 8080))\nclient.send(b'GET / HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n')\nresponse = client.recv(4096)\nprint(response.decode())`,
    sampleCode2: `// TCP 3-Way Handshake Representation:\n// 1. Client -> SYN (Seq=x) -> Server\n// 2. Server -> SYN-ACK (Seq=y, Ack=x+1) -> Client\n// 3. Client -> ACK (Ack=y+1) -> Server (ESTABLISHED)`,
    ch2Title: 'OSI Layer Architecture & TCP 3-Way Handshake',
  },
  {
    title: 'Theory of Computation',
    slug: 'toc',
    shortTitle: 'TOC & Automata',
    category: 'Core Computer Science',
    iconName: 'Binary',
    description: 'Deterministic Finite Automata (DFA), NFA, Regular Expressions, Context-Free Grammars, and Turing Machines.',
    lang: 'python',
    codeExt: 'dfa_simulator.py',
    sampleCode1: `# Simple DFA Simulator for strings ending in '01'\ndef dfa_sim(s):\n    state = 'q0'\n    for ch in s:\n        if state == 'q0': state = 'q1' if ch == '0' else 'q0'\n        elif state == 'q1': state = 'q2' if ch == '1' else 'q1'\n        elif state == 'q2': state = 'q1' if ch == '0' else 'q0'\n    return state == 'q2'`,
    sampleCode2: `// Chomsky Hierarchy of Formal Languages:\n// Type 3: Regular Languages (Finite Automata)\n// Type 2: Context-Free Languages (Pushdown Automata)\n// Type 1: Context-Sensitive Languages\n// Type 0: Recursively Enumerable (Turing Machine)`,
    ch2Title: 'Finite State Automata & Regular Expressions',
  },
  {
    title: 'Compiler Design',
    slug: 'compiler',
    shortTitle: 'Compiler Design',
    category: 'Core Computer Science',
    iconName: 'Code2',
    description: 'Lexical analysis (Tokenization), Syntax analysis (LL/LR Parsing), Abstract Syntax Trees (AST), and Code generation.',
    lang: 'python',
    codeExt: 'lexer.py',
    sampleCode1: `import re\n\nTOKEN_TYPES = [\n    ('NUMBER', r'\\d+'),\n    ('PLUS', r'\\+'),\n    ('MINUS', r'-'),\n    ('TIMES', r'\\*'),\n]\n\ndef tokenize(code):\n    # Lexical Analyzer Scanner\n    tokens = []\n    for kind, regex in TOKEN_TYPES:\n        for m in re.finditer(regex, code):\n            tokens.append((kind, m.group()))\n    return tokens`,
    sampleCode2: `// AST Node Structure\nclass ASTNode {\n    String type;\n    ASTNode left;\n    ASTNode right;\n}`,
    ch2Title: 'Lexical Tokenization & Syntax Parsing (AST)',
  },
  {
    title: 'COA',
    slug: 'coa',
    shortTitle: 'COA Architecture',
    category: 'Core Computer Science',
    iconName: 'Layers',
    description: 'Computer Organization & Architecture, Von Neumann machine, ALU design, Instruction pipelines, and Cache mapping.',
    lang: 'c',
    codeExt: 'pipeline.c',
    sampleCode1: `// Instruction Cycle: Fetch -> Decode -> Execute -> Memory Access -> Write Back\ntypedef struct {\n    unsigned int pc;\n    unsigned int instruction_register;\n    int registers[32];\n} CPU_State;`,
    sampleCode2: `// Direct Mapped Cache Calculation:\n// Cache Index = (Memory Address / Block Size) % Number of Cache Blocks`,
    ch2Title: 'Instruction Pipeline & Cache Memory Hierarchy',
  },
  {
    title: 'DSA',
    slug: 'dsa',
    shortTitle: 'DSA',
    category: 'Core Computer Science',
    iconName: 'Binary',
    description: 'Data Structures and Algorithms, asymptotic Big-O analysis, Recursion, Dynamic Programming, and Graph traversals.',
    lang: 'cpp',
    codeExt: 'binary_search.cpp',
    sampleCode1: `#include <vector>\nusing namespace std;\n\nint binarySearch(const vector<int>& arr, int target) {\n    int l = 0, r = arr.size() - 1;\n    while (l <= r) {\n        int mid = l + (r - l) / 2;\n        if (arr[mid] == target) return mid;\n        if (arr[mid] < target) l = mid + 1;\n        else r = mid - 1;\n    }\n    return -1;\n}`,
    sampleCode2: `// DFS Graph Traversal\nvoid dfs(int u, vector<bool>& vis, const vector<vector<int>>& adj) {\n    vis[u] = true;\n    for (int v : adj[u]) if (!vis[v]) dfs(v, vis, adj);\n}`,
    ch2Title: 'Time Complexity Analysis & Recursion Mechanics',
  },
  {
    title: 'Algorithms',
    slug: 'algorithms',
    shortTitle: 'Algorithms',
    category: 'Core Computer Science',
    iconName: 'Binary',
    description: 'Divide and conquer, Greedy techniques, Dynamic Programming (Tabulation/Memoization), Backtracking, and Dijkstra.',
    lang: 'python',
    codeExt: 'quick_sort.py',
    sampleCode1: `def quick_sort(arr):\n    if len(arr) <= 1: return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    mid = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quick_sort(left) + mid + quick_sort(right)`,
    sampleCode2: `# 0/1 Knapsack Dynamic Programming\ndef knapsack(W, wt, val, n):\n    dp = [[0 for _ in range(W + 1)] for _ in range(n + 1)]\n    for i in range(n + 1):\n        for w in range(W + 1):\n            if i == 0 or w == 0: dp[i][w] = 0\n            elif wt[i-1] <= w:\n                dp[i][w] = max(val[i-1] + dp[i-1][w-wt[i-1]], dp[i-1][w])\n            else: dp[i][w] = dp[i-1][w]\n    return dp[n][W]`,
    ch2Title: 'Divide & Conquer, Sorting & Dynamic Programming',
  },
  {
    title: 'Data Structures',
    slug: 'datastructures',
    shortTitle: 'Data Structures',
    category: 'Core Computer Science',
    iconName: 'Binary',
    description: 'Arrays, Linked Lists, Stacks, Queues, Binary Trees, Binary Search Trees, Heaps, Hash Tables, and Trie graphs.',
    lang: 'cpp',
    codeExt: 'linked_list.cpp',
    sampleCode1: `struct Node {\n    int val;\n    Node* next;\n    Node(int x) : val(x), next(nullptr) {}\n};\n\nNode* insertHead(Node* head, int val) {\n    Node* newNode = new Node(val);\n    newNode->next = head;\n    return newNode;\n}`,
    sampleCode2: `// Min-Heap Priority Queue in C++\n#include <queue>\nstd::priority_queue<int, std::vector<int>, std::greater<int>> minHeap;`,
    ch2Title: 'Linear vs Non-Linear Structures & Memory Layouts',
  },
  {
    title: 'Discrete Mathematics',
    slug: 'discrete-math',
    shortTitle: 'Discrete Math',
    category: 'Core Computer Science',
    iconName: 'Binary',
    description: 'Set theory, Propositional logic, Relations, Graph theory, Combinatorics, Recurrence relations, and Boolean algebra.',
    lang: 'python',
    codeExt: 'logic.py',
    sampleCode1: `# Propositional Logic Evaluation\ndef implies(p, q):\n    return not p or q\n\n# Truth Table for P -> Q\nfor p in [True, False]:\n    for q in [True, False]:\n        print(f"{p} -> {q} = {implies(p, q)}")`,
    sampleCode2: `// Euler's Formula for Planar Graphs:\n// Vertices - Edges + Faces = 2 (V - E + F = 2)`,
    ch2Title: 'Propositional Logic, Sets & Graph Combinatorics',
  },
  {
    title: 'Software Engineering',
    slug: 'software-engineering',
    shortTitle: 'Software Engineering',
    category: 'Core Computer Science',
    iconName: 'BookOpen',
    description: 'Software development life cycle (SDLC), Agile Scrum, Clean Code principles, Design Patterns, and UML diagrams.',
    lang: 'java',
    codeExt: 'Singleton.java',
    sampleCode1: `// Singleton Design Pattern (Thread-safe Double-Checked Locking)\npublic class DatabaseConnection {\n    private static volatile DatabaseConnection instance;\n    private DatabaseConnection() {}\n    public static DatabaseConnection getInstance() {\n        if (instance == null) {\n            synchronized (DatabaseConnection.class) {\n                if (instance == null) instance = new DatabaseConnection();\n            }\n        }\n        return instance;\n    }\n}`,
    sampleCode2: `// SOLID Principles:\n// S: Single Responsibility\n// O: Open-Closed\n// L: Liskov Substitution\n// I: Interface Segregation\n// D: Dependency Inversion`,
    ch2Title: 'Agile SDLC, SOLID Principles & Design Patterns',
  },
  {
    title: 'OOPs Concepts',
    slug: 'oops',
    shortTitle: 'OOPs Concepts',
    category: 'Core Computer Science',
    iconName: 'Code2',
    description: 'The 4 Pillars of Object-Oriented Programming: Encapsulation, Abstraction, Inheritance, and Polymorphism.',
    lang: 'java',
    codeExt: 'Polymorphism.java',
    sampleCode1: `abstract class Animal {\n    abstract void makeSound();\n}\n\nclass Dog extends Animal {\n    void makeSound() { System.out.println("Bark"); }\n}\n\nclass Cat extends Animal {\n    void makeSound() { System.out.println("Meow"); }\n}`,
    sampleCode2: `// Encapsulation with Getters and Setters\npublic class BankAccount {\n    private double balance;\n    public double getBalance() { return balance; }\n    public void deposit(double amt) { if (amt > 0) balance += amt; }\n}`,
    ch2Title: 'The 4 Pillars: Encapsulation, Inheritance, Polymorphism',
  },
  {
    title: 'Computer Graphics',
    slug: 'computer-graphics',
    shortTitle: 'Computer Graphics',
    category: 'Core Computer Science',
    iconName: 'Layers',
    description: 'Rasterization, Bresenham line algorithm, 2D/3D matrix transformations, Shaders, Ray tracing, and OpenGL pipelines.',
    lang: 'c',
    codeExt: 'bresenham.c',
    sampleCode1: `void drawLine(int x0, int y0, int x1, int y1) {\n    int dx = abs(x1 - x0), sx = x0 < x1 ? 1 : -1;\n    int dy = -abs(y1 - y0), sy = y0 < y1 ? 1 : -1;\n    int err = dx + dy, e2;\n    while (1) {\n        plot(x0, y0);\n        if (x0 == x1 && y0 == y1) break;\n        e2 = 2 * err;\n        if (e2 >= dy) { err += dy; x0 += sx; }\n        if (e2 <= dx) { err += dx; y0 += sy; }\n    }\n}`,
    sampleCode2: `// 2D Rotation Matrix:\n// [x'] = [cos(theta)  -sin(theta)] * [x]\n// [y']   [sin(theta)   cos(theta)]   [y]`,
    ch2Title: 'Bresenham Algorithm & 2D/3D Matrix Transformations',
  },

  // --- Programming Languages ---
  {
    title: 'Python',
    slug: 'python',
    shortTitle: 'Python',
    category: 'Programming Languages',
    iconName: 'FileCode2',
    description: 'Python syntax, list comprehensions, decorators, generators, dunder methods, and standard library modules.',
    lang: 'python',
    codeExt: 'main.py',
    sampleCode1: `# Python Decorator Pattern\ndef timer_decorator(func):\n    def wrapper(*args, **kwargs):\n        print(f"Calling {func.__name__}")\n        return func(*args, **kwargs)\n    return wrapper\n\n@timer_decorator\ndef compute():\n    return sum(x**2 for x in range(100))\n\nprint("Result:", compute())`,
    sampleCode2: `# Generator for Infinite Fib Numbers\ndef fib_generator():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b`,
    ch2Title: 'Python Decorators, Generators & Dunder Methods',
  },
  {
    title: 'Java',
    slug: 'java',
    shortTitle: 'Java',
    category: 'Programming Languages',
    iconName: 'Coffee',
    description: 'Java 21 Virtual Threads, Streams API, Records, Sealed classes, JVM memory spaces, and garbage collection.',
    lang: 'java',
    codeExt: 'Main.java',
    sampleCode1: `public record Student(String name, int grade) {}\n\npublic class Main {\n    public static void main(String[] args) {\n        var student = new Student("Alex", 95);\n        System.out.println("Enrolled: " + student.name());\n    }\n}`,
    sampleCode2: `// Java 21 Project Loom: Lightweight Virtual Threads\nThread.startVirtualThread(() -> {\n    System.out.println("Running in virtual thread: " + Thread.currentThread());\n});`,
    ch2Title: 'Java Streams API & Virtual Threads (Java 21)',
  },
  {
    title: 'C++',
    slug: 'cpp',
    shortTitle: 'C++',
    category: 'Core Languages',
    iconName: 'Cpu',
    description: 'Modern C++20, RAII resource management, Smart pointers (unique/shared), Move semantics, and Templates.',
    lang: 'cpp',
    codeExt: 'smart_ptr.cpp',
    sampleCode1: `#include <iostream>\n#include <memory>\n\nclass Resource {\npublic:\n    Resource() { std::cout << "Allocated\\n"; }\n    ~Resource() { std::cout << "Freed automatically!\\n"; }\n};\n\nint main() {\n    std::unique_ptr<Resource> ptr = std::make_unique<Resource>();\n    return 0;\n}`,
    sampleCode2: `// Template Function in C++\ntemplate <typename T>\nT maxVal(T a, T b) {\n    return (a > b) ? a : b;\n}`,
    ch2Title: 'C++ Smart Pointers, RAII & Move Semantics',
  },
  {
    title: 'C Language',
    slug: 'c',
    shortTitle: 'C Language',
    category: 'Core Languages',
    iconName: 'Terminal',
    description: 'Pointers, pointer arithmetic, dynamic memory allocation (malloc/free), structs, unions, and POSIX headers.',
    lang: 'c',
    codeExt: 'pointers.c',
    sampleCode1: `#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int* arr = (int*)malloc(5 * sizeof(int));\n    for (int i = 0; i < 5; i++) arr[i] = i * 10;\n    for (int i = 0; i < 5; i++) printf("%d ", *(arr + i));\n    free(arr);\n    return 0;\n}`,
    sampleCode2: `// Struct Memory Layout & Bitfields\nstruct Flags {\n    unsigned int is_ready : 1;\n    unsigned int error_code : 4;\n};`,
    ch2Title: 'C Pointers, Pointer Arithmetic & Dynamic Memory',
  },
  {
    title: 'C#',
    slug: 'csharp',
    shortTitle: 'C#',
    category: 'Programming Languages',
    iconName: 'Code2',
    description: '.NET 8/9 C#, LINQ queries, Async/Await Tasks, Dependency Injection, and ASP.NET Core web microservices.',
    lang: 'csharp',
    codeExt: 'Program.cs',
    sampleCode1: `using System;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        int[] numbers = { 1, 2, 3, 4, 5, 6 };\n        var evens = numbers.Where(n => n % 2 == 0);\n        Console.WriteLine($"Evens: {string.Join(", ", evens)}");\n    }\n}`,
    sampleCode2: `public record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary);\n// Minimal API in ASP.NET Core\napp.MapGet("/weather", () => new WeatherForecast(DateOnly.FromDateTime(DateTime.Now), 25, "Sunny"));`,
    ch2Title: 'C# LINQ Expressions & Modern .NET Async/Await',
  },
  {
    title: 'Go Language',
    slug: 'go',
    shortTitle: 'Go Language',
    category: 'Programming Languages',
    iconName: 'Terminal',
    description: 'Go concurrency with Goroutines, Channels, Select statements, Struct composition, Interfaces, and standard net/http.',
    lang: 'go',
    codeExt: 'main.go',
    sampleCode1: `package main\nimport (\n\t"fmt"\n\t"time"\n)\n\nfunc worker(ch chan string) {\n\ttime.Sleep(time.Millisecond * 500)\n\tch <- "Work complete!"\n}\n\nfunc main() {\n\tch := make(chan string)\n\tgo worker(ch)\n\tfmt.Println(<-ch)\n}`,
    sampleCode2: `// Go Interface Implementation\ntype Writer interface {\n    Write([]byte) (int, error)\n}`,
    ch2Title: 'Go Concurrency: Goroutines & Buffered Channels',
  },
  {
    title: 'Rust',
    slug: 'rust',
    shortTitle: 'Rust',
    category: 'Programming Languages',
    iconName: 'Cpu',
    description: 'Memory safety without garbage collection, Ownership, Borrow Checker, Lifetimes, Traits, and Pattern Matching.',
    lang: 'rust',
    codeExt: 'main.rs',
    sampleCode1: `fn main() {\n    let s1 = String::from("hello");\n    let len = calculate_length(&s1); // Borrow with reference\n    println!("Length of '{}' is {}", s1, len);\n}\n\nfn calculate_length(s: &String) -> usize {\n    s.len()\n}`,
    sampleCode2: `// Rust Option/Result pattern matching\nfn divide(a: f64, b: f64) -> Result<f64, String> {\n    if b == 0.0 { Err(String::from("Divide by zero")) }\n    else { Ok(a / b) }\n}`,
    ch2Title: 'Rust Ownership, Borrow Checker & Lifetimes',
  },
  {
    title: 'PHP',
    slug: 'php',
    shortTitle: 'PHP',
    category: 'Programming Languages',
    iconName: 'FileCode',
    description: 'Modern PHP 8.3, typed properties, match expressions, Composer package management, and Laravel architecture.',
    lang: 'php',
    codeExt: 'index.php',
    sampleCode1: `<?php\nclass Developer {\n    public function __construct(public string $name, public string $level) {}\n}\n\n$dev = new Developer("Alex", "Senior");\necho "Engineer: " . $dev->name;`,
    sampleCode2: `// PHP 8 Match Expression\n$status = 200;\n$message = match($status) {\n    200 => 'OK',\n    404 => 'Not Found',\n    default => 'Unknown',\n};`,
    ch2Title: 'Modern PHP 8.x Features & Composer Ecosystem',
  },
  {
    title: 'Kotlin',
    slug: 'kotlin',
    shortTitle: 'Kotlin',
    category: 'Programming Languages',
    iconName: 'Coffee',
    description: 'Kotlin for Android and JVM backend, Null safety (?./?:), Coroutines, Data classes, and Extension functions.',
    lang: 'kotlin',
    codeExt: 'Main.kt',
    sampleCode1: `data class User(val id: Int, val username: String, val email: String?)\n\nfun main() {\n    val user = User(1, "nextera", null)\n    val email = user.email ?: "no-email@nextera.com"\n    println("User email: $email")\n}`,
    sampleCode2: `// Kotlin Extension Function\nfun String.toSlug(): String = this.lowercase().replace(" ", "-")`,
    ch2Title: 'Kotlin Null Safety, Coroutines & Extension Functions',
  },
  {
    title: 'Swift',
    slug: 'swift',
    shortTitle: 'Swift',
    category: 'Programming Languages',
    iconName: 'FileCode',
    description: 'Apple iOS/macOS engineering, Swift optionals, Protocol-oriented programming, Structs vs Classes, and SwiftUI.',
    lang: 'swift',
    codeExt: 'main.swift',
    sampleCode1: `import Foundation\n\nstruct TechCourse {\n    let title: String\n    var enrolled: Int\n}\n\nvar course = TechCourse(title: "iOS Engineering", enrolled: 120)\nprint("Course: \\(course.title)")`,
    sampleCode2: `// Protocol in Swift\nprotocol IdentifiableItem {\n    var id: UUID { get }\n}`,
    ch2Title: 'Swift Optionals & Protocol-Oriented Architecture',
  },
  {
    title: 'Dart & Flutter',
    slug: 'dart',
    shortTitle: 'Dart & Flutter',
    category: 'Programming Languages',
    iconName: 'Layers',
    description: 'Dart language fundamentals, Flutter Widget tree, Stateless vs Stateful, Provider/Bloc, and cross-platform UI.',
    lang: 'dart',
    codeExt: 'main.dart',
    sampleCode1: `import 'package:flutter/material.dart';\n\nvoid main() => runApp(const MyApp());\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n  @override\n  Widget build(BuildContext context) {\n    return const MaterialApp(home: Scaffold(body: Center(child: Text('Hello Flutter!'))));\n  }\n}`,
    sampleCode2: `// Async Future in Dart\nFuture<String> fetchUser() async {\n  await Future.delayed(const Duration(seconds: 1));\n  return 'NextEra Student';\n}`,
    ch2Title: 'Flutter Widget Lifecycle & State Management',
  },

  // --- Databases & Storage ---
  {
    title: 'SQL',
    slug: 'sql',
    shortTitle: 'SQL',
    category: 'Databases & Storage',
    iconName: 'Database',
    description: 'Structured Query Language, SELECT joins, subqueries, aggregation, window functions, and indexing.',
    lang: 'sql',
    codeExt: 'queries.sql',
    sampleCode1: `-- Inner Join and Group By Aggregation\nSELECT \n  c.category_name, \n  COUNT(p.id) AS total_products,\n  AVG(p.price) AS average_price\nFROM categories c\nJOIN products p ON c.id = p.category_id\nGROUP BY c.category_name\nHAVING COUNT(p.id) > 5;`,
    sampleCode2: `-- Window Function Example\nSELECT \n  name, \n  salary, \n  DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) as rank\nFROM employees;`,
    ch2Title: 'Advanced SQL Joins & Window Analytic Functions',
  },
  {
    title: 'PostgreSQL',
    slug: 'postgresql',
    shortTitle: 'PostgreSQL',
    category: 'Databases & Storage',
    iconName: 'Database',
    description: 'Enterprise relational database, JSONB query operators, GIN/GiST indexes, connection pooling (PgBouncer), and CTEs.',
    lang: 'sql',
    codeExt: 'postgres.sql',
    sampleCode1: `-- JSONB Data Querying in PostgreSQL\nCREATE TABLE app_events (\n  id SERIAL PRIMARY KEY,\n  payload JSONB NOT NULL\n);\n\nSELECT * FROM app_events WHERE payload @> '{"action": "signup"}';`,
    sampleCode2: `-- Common Table Expression (CTE)\nWITH HighEarners AS (\n  SELECT * FROM employees WHERE salary > 100000\n)\nSELECT department, COUNT(*) FROM HighEarners GROUP BY department;`,
    ch2Title: 'PostgreSQL JSONB Queries, GIN Indexing & CTEs',
  },
  {
    title: 'MySQL',
    slug: 'mysql',
    shortTitle: 'MySQL',
    category: 'Databases & Storage',
    iconName: 'Database',
    description: 'InnoDB storage engine, B+ Tree primary clustered indexes, master-replica replication, and query EXPLAIN plans.',
    lang: 'sql',
    codeExt: 'mysql.sql',
    sampleCode1: `-- Indexing in InnoDB Engine\nCREATE TABLE orders (\n  order_id INT AUTO_INCREMENT PRIMARY KEY,\n  user_id INT NOT NULL,\n  status VARCHAR(20),\n  KEY idx_user_status (user_id, status)\n) ENGINE=InnoDB;`,
    sampleCode2: `EXPLAIN SELECT * FROM orders WHERE user_id = 42 AND status = 'COMPLETED';`,
    ch2Title: 'MySQL InnoDB Clustered Indexes & Replication',
  },
  {
    title: 'MongoDB',
    slug: 'mongodb',
    shortTitle: 'MongoDB',
    category: 'Databases & Storage',
    iconName: 'Database',
    description: 'Document database, BSON schemas, Aggregation pipeline ($match, $group, $lookup), Replica Sets, and sharding.',
    lang: 'javascript',
    codeExt: 'pipeline.js',
    sampleCode1: `// MongoDB Aggregation Pipeline\ndb.orders.aggregate([\n  { $match: { status: "A" } },\n  { $group: { _id: "$cust_id", total: { $sum: "$amount" } } },\n  { $sort: { total: -1 } }\n]);`,
    sampleCode2: `// Compound Index Creation\ndb.users.createIndex({ email: 1, role: 1 }, { unique: true });`,
    ch2Title: 'MongoDB Aggregation Pipelines & Compound Indexes',
  },
  {
    title: 'Redis',
    slug: 'redis',
    shortTitle: 'Redis',
    category: 'Databases & Storage',
    iconName: 'Database',
    description: 'In-memory key-value store, caching strategies (Cache-Aside, Write-Through), Pub/Sub, Hashes, and TTL expiry.',
    lang: 'javascript',
    codeExt: 'cache.js',
    sampleCode1: `// Redis Cache-Aside Pattern\nasync function getCachedProfile(userId) {\n  const cached = await redis.get(\`user:\${userId}\`);\n  if (cached) return JSON.parse(cached);\n  const user = await db.users.findById(userId);\n  await redis.setex(\`user:\${userId}\`, 3600, JSON.stringify(user));\n  return user;\n}`,
    sampleCode2: `// Atomic Counter and Rate Limiting\nawait redis.incr('rate_limit:user_123');\nawait redis.expire('rate_limit:user_123', 60);`,
    ch2Title: 'Redis Caching Strategies & Distributed Key Eviction',
  },

  // --- DevOps & Cloud ---
  {
    title: 'Git & GitHub',
    slug: 'git',
    shortTitle: 'Git & GitHub',
    category: 'DevOps & Cloud',
    iconName: 'Terminal',
    description: 'Version control, commit graphs, branching strategies (Git Flow), interactive rebasing, merge conflicts, and PRs.',
    lang: 'bash',
    codeExt: 'git_workflow.sh',
    sampleCode1: `# Essential Git Feature Workflow\ngit checkout -b feature/user-auth\ngit add .\ngit commit -m "feat(auth): add JWT login authentication"\ngit push origin feature/user-auth`,
    sampleCode2: `# Interactive Rebase & Squash\ngit fetch origin\ngit rebase -i HEAD~3`,
    ch2Title: 'Git Branching Models, Rebasing & Conflict Resolution',
  },
  {
    title: 'DevOps',
    slug: 'devops',
    shortTitle: 'DevOps',
    category: 'DevOps & Cloud',
    iconName: 'Cloud',
    description: 'DevOps culture, CI/CD automation pipelines, Infrastructure as Code (IaC), zero-downtime rolling updates, and monitoring.',
    lang: 'yaml',
    codeExt: 'pipeline.yml',
    sampleCode1: `name: Production Deployment\non:\n  push:\n    branches: [main]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n      - run: npm ci && npm test`,
    sampleCode2: `# Zero-Downtime Blue-Green Deployment Strategy\n# 1. Deploy Green environment alongside Active Blue\n# 2. Run automated smoke tests on Green\n# 3. Switch reverse-proxy load balancer traffic to Green`,
    ch2Title: 'DevOps CI/CD Pipelines & Blue-Green Deployments',
  },
  {
    title: 'Docker',
    slug: 'docker',
    shortTitle: 'Docker',
    category: 'DevOps & Cloud',
    iconName: 'Cloud',
    description: 'Containerization, Dockerfiles, multi-stage production builds, layer caching, Docker Compose, and bridge networking.',
    lang: 'dockerfile',
    codeExt: 'Dockerfile',
    sampleCode1: `# Multi-stage lightweight production container\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCMD ["node", "dist/index.js"]`,
    sampleCode2: `version: '3.8'\nservices:\n  web:\n    build: .\n    ports: ["3000:3000"]\n  redis:\n    image: redis:alpine`,
    ch2Title: 'Dockerfile Multi-Stage Builds & Docker Compose',
  },
  {
    title: 'Kubernetes',
    slug: 'kubernetes',
    shortTitle: 'Kubernetes',
    category: 'DevOps & Cloud',
    iconName: 'Cloud',
    description: 'Container orchestration, Pods, Deployments, ReplicaSets, ClusterIP/LoadBalancer Services, Ingress, and ConfigMaps.',
    lang: 'yaml',
    codeExt: 'deployment.yaml',
    sampleCode1: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: api-deployment\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: api\n  template:\n    metadata:\n      labels:\n        app: api\n    spec:\n      containers:\n      - name: api\n        image: nextera/api:latest\n        ports:\n        - containerPort: 5000`,
    sampleCode2: `apiVersion: v1\nkind: Service\nmetadata:\n  name: api-service\nspec:\n  type: LoadBalancer\n  ports:\n  - port: 80\n    targetPort: 5000\n  selector:\n    app: api`,
    ch2Title: 'Kubernetes Pods, Deployments & Service Discovery',
  },
  {
    title: 'Linux & Shell',
    slug: 'linux',
    shortTitle: 'Linux & Shell',
    category: 'DevOps & Cloud',
    iconName: 'Terminal',
    description: 'Bash scripting, file permissions (chmod/chown), process signals (kill/top), grep/awk/sed text streams, and cron jobs.',
    lang: 'bash',
    codeExt: 'backup.sh',
    sampleCode1: `#!/bin/bash\n# Linux Server Monitoring Script\nMEM_USAGE=$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')\necho "Current Memory Usage: $MEM_USAGE"\n\nif [ ! -d "/backup" ]; then\n  mkdir -p /backup\nfi`,
    sampleCode2: `# Pipe and Filter Data with grep and awk\ncat access.log | grep "404" | awk '{print $7}' | sort | uniq -c | sort -nr`,
    ch2Title: 'Bash Shell Scripting & Linux Process Management',
  },
  {
    title: 'AWS Cloud',
    slug: 'aws',
    shortTitle: 'AWS Cloud',
    category: 'DevOps & Cloud',
    iconName: 'Cloud',
    description: 'Amazon Web Services, EC2 compute instances, S3 object buckets, IAM roles/policies, Lambda serverless, and VPC.',
    lang: 'bash',
    codeExt: 'aws_cli.sh',
    sampleCode1: `# AWS CLI S3 File Upload\naws s3 cp ./build/ s3://nextera-production-assets/ --recursive --acl public-read`,
    sampleCode2: `# IAM Policy Document Sample:\n{\n  "Version": "2012-10-17",\n  "Statement": [{\n    "Effect": "Allow",\n    "Action": "s3:GetObject",\n    "Resource": "arn:aws:s3:::nextera-bucket/*"\n  }]\n}`,
    ch2Title: 'AWS Core Services: EC2, S3, IAM & VPC Networking',
  },
  {
    title: 'System Design',
    slug: 'systemdesign',
    shortTitle: 'System Design',
    category: 'Cloud & Architecture',
    iconName: 'Network',
    description: 'High-Level Architecture (HLD), horizontal scaling, Load Balancers, Database sharding, CAP Theorem, and CDNs.',
    lang: 'javascript',
    codeExt: 'consistent_hashing.js',
    sampleCode1: `// Consistent Hashing Concept\n// Maps incoming user keys to a distributed ring of database nodes\nclass HashRing {\n  constructor(nodes = []) {\n    this.nodes = nodes;\n  }\n  getNode(key) {\n    const hash = this.hashFunc(key);\n    return this.nodes[hash % this.nodes.length];\n  }\n  hashFunc(str) {\n    let hash = 0;\n    for (let i = 0; i < str.length; i++) hash += str.charCodeAt(i);\n    return hash;\n  }\n}`,
    sampleCode2: `// CAP Theorem Tradeoffs:\n// Consistency (C) vs Availability (A) vs Partition Tolerance (P)\n// In distributed networks, you must choose either CP or AP under network partitions.`,
    ch2Title: 'System Scaling: Load Balancing, Caching & CAP Theorem',
  },
  {
    title: 'Microservices',
    slug: 'microservices',
    shortTitle: 'Microservices',
    category: 'Cloud & Architecture',
    iconName: 'Network',
    description: 'Decoupled services, API Gateway routing, Event-Driven Architecture with Kafka/RabbitMQ, and circuit breakers.',
    lang: 'javascript',
    codeExt: 'gateway.js',
    sampleCode1: `// API Gateway Reverse Proxy Routing\nconst httpProxy = require('express-http-proxy');\napp.use('/auth', httpProxy('http://auth-service:5001'));\napp.use('/orders', httpProxy('http://order-service:5002'));\napp.use('/payments', httpProxy('http://payment-service:5003'));`,
    sampleCode2: `// Event-Driven Message Publishing\nawait kafkaProducer.send({\n  topic: 'user-registered',\n  messages: [{ value: JSON.stringify({ userId: 123, email: 'user@test.com' }) }]\n});`,
    ch2Title: 'API Gateway Routing & Event-Driven Message Queues',
  },
  {
    title: 'Nginx',
    slug: 'nginx',
    shortTitle: 'Nginx',
    category: 'Cloud & Architecture',
    iconName: 'Network',
    description: 'High-performance web server, Reverse Proxy, SSL/TLS termination, Gzip compression, and upstream load balancing.',
    lang: 'nginx',
    codeExt: 'nginx.conf',
    sampleCode1: `upstream backend_cluster {\n  server 10.0.0.1:5000 weight=3;\n  server 10.0.0.2:5000;\n}\n\nserver {\n  listen 80;\n  server_name nexteracoders.com;\n  location / {\n    proxy_pass http://backend_cluster;\n    proxy_set_header Host $host;\n  }\n}`,
    sampleCode2: `location ~* \\.(jpg|jpeg|png|gif|ico|css|js)$ {\n  expires 30d;\n  add_header Cache-Control "public, no-transform";\n}`,
    ch2Title: 'Nginx Reverse Proxy & SSL Termination Configuration',
  },
  {
    title: 'CI/CD Pipelines',
    slug: 'cicd',
    shortTitle: 'CI/CD Pipelines',
    category: 'DevOps & Cloud',
    iconName: 'Cloud',
    description: 'Continuous Integration & Continuous Delivery, automated testing, semantic versioning, and container registries.',
    lang: 'yaml',
    codeExt: 'github_actions.yml',
    sampleCode1: `name: CI Validation\non: [pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n      - uses: actions/setup-node@v3\n        with: { node-version: 20 }\n      - run: npm ci\n      - run: npm run lint\n      - run: npm test`,
    sampleCode2: `- name: Publish Docker Container\n  run: |\n    docker build -t registry.example.com/app:v1.0 .\n    docker push registry.example.com/app:v1.0`,
    ch2Title: 'Automated Testing, Linting & Container Deployment Steps',
  },

  // --- Security & Testing ---
  {
    title: 'Cybersecurity',
    slug: 'cybersecurity',
    shortTitle: 'Cybersecurity',
    category: 'Security & Testing',
    iconName: 'ShieldCheck',
    description: 'Network defense, OWASP Top 10 vulnerabilities, XSS, CSRF, SQL Injection, cryptographic hashing (bcrypt/SHA-256).',
    lang: 'javascript',
    codeExt: 'security.js',
    sampleCode1: `// Password Hashing with Salt using bcrypt\nconst bcrypt = require('bcrypt');\n\nasync function hashPassword(plainText) {\n  const saltRounds = 12;\n  const hash = await bcrypt.hash(plainText, saltRounds);\n  return hash;\n}`,
    sampleCode2: `// Sanitizing inputs against Cross-Site Scripting (XSS)\nconst sanitizeHtml = require('sanitize-html');\nconst cleanHtml = sanitizeHtml(dirtyUserInput, { allowedTags: ['b', 'i', 'em'] });`,
    ch2Title: 'OWASP Top 10 Vulnerabilities & Cryptographic Hashing',
  },
  {
    title: 'Ethical Hacking',
    slug: 'ethical-hacking',
    shortTitle: 'Ethical Hacking',
    category: 'Security & Testing',
    iconName: 'ShieldCheck',
    description: 'Penetration testing phases, reconnaissance (Nmap), vulnerability scanning, packet sniffing (Wireshark), and reports.',
    lang: 'bash',
    codeExt: 'nmap_scan.sh',
    sampleCode1: `# Network Reconnaissance with Nmap (Authorized Testing Only)\nnmap -sV -sC -p 22,80,443 target.example.com`,
    sampleCode2: `# Inspect network interfaces and open listening ports\nnetstat -tulnp`,
    ch2Title: 'Penetration Testing Methodology & Network Recon',
  },
  {
    title: 'Software Testing',
    slug: 'testing',
    shortTitle: 'Software Testing',
    category: 'Security & Testing',
    iconName: 'CheckCircle2',
    description: 'Unit testing with Jest/Vitest, integration tests, end-to-end (E2E) testing with Playwright, and test coverage metrics.',
    lang: 'javascript',
    codeExt: 'math.test.js',
    sampleCode1: `import { describe, it, expect } from 'vitest';\n\nfunction add(a, b) { return a + b; }\n\ndescribe('Math Calculations', () => {\n  it('correctly adds numbers', () => {\n    expect(add(2, 3)).toBe(5);\n  });\n});`,
    sampleCode2: `// Playwright E2E Test\nimport { test, expect } from '@playwright/test';\ntest('homepage has title', async ({ page }) => {\n  await page.goto('http://localhost:5173');\n  await expect(page).toHaveTitle(/NextEra Coders/);\n});`,
    ch2Title: 'Unit Testing with Jest & E2E Testing with Playwright',
  },

  // --- AI & Data Science ---
  {
    title: 'Machine Learning',
    slug: 'ml',
    shortTitle: 'Machine Learning',
    category: 'AI & Data Science',
    iconName: 'Sparkles',
    description: 'Supervised & Unsupervised learning, Scikit-learn, Linear/Logistic regression, Decision trees, and model evaluation.',
    lang: 'python',
    codeExt: 'train.py',
    sampleCode1: `from sklearn.linear_model import LogisticRegression\nimport numpy as np\n\nX = np.array([[1, 2], [2, 3], [3, 4], [8, 9], [9, 10]])\ny = np.array([0, 0, 0, 1, 1])\n\nmodel = LogisticRegression()\nmodel.fit(X, y)\nprint("Prediction:", model.predict([[4, 5]]))`,
    sampleCode2: `from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)`,
    ch2Title: 'Supervised Learning Algorithms & Train-Test Splits',
  },
  {
    title: 'Deep Learning',
    slug: 'deep-learning',
    shortTitle: 'Deep Learning',
    category: 'AI & Data Science',
    iconName: 'Sparkles',
    description: 'Neural networks, PyTorch, Backpropagation, Convolutional Neural Networks (CNNs), and Transformer attention mechanisms.',
    lang: 'python',
    codeExt: 'nn_pytorch.py',
    sampleCode1: `import torch\nimport torch.nn as nn\n\nclass SimpleMLP(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.layers = nn.Sequential(\n            nn.Linear(10, 64),\n            nn.ReLU(),\n            nn.Linear(64, 2)\n        )\n    def forward(self, x):\n        return self.layers(x)`,
    sampleCode2: `# Loss Function and Optimizer in PyTorch\nloss_fn = nn.CrossEntropyLoss()\noptimizer = torch.optim.Adam(model.parameters(), lr=0.001)`,
    ch2Title: 'Neural Network Forward Propagation & PyTorch Models',
  },
  {
    title: 'Artificial Intelligence',
    slug: 'ai',
    shortTitle: 'Artificial Intelligence',
    category: 'AI & Data Science',
    iconName: 'Sparkles',
    description: 'Search algorithms (A*, Minimax), Expert systems, Knowledge graphs, Reinforcement Learning, and Heuristic evaluation.',
    lang: 'python',
    codeExt: 'a_star.py',
    sampleCode1: `import heapq\n\ndef a_star(graph, start, goal, h):\n    open_set = [(h(start), 0, start, [])]\n    while open_set:\n        est, cost, curr, path = heapq.heappop(open_set)\n        if curr == goal: return path + [curr]\n        for neighbor, weight in graph.get(curr, []):\n            heapq.heappush(open_set, (cost + weight + h(neighbor), cost + weight, neighbor, path + [curr]))`,
    sampleCode2: `// Minimax with Alpha-Beta Pruning\nfunction minimax(node, depth, isMaximizing, alpha, beta) { ... }`,
    ch2Title: 'A* Search Heuristics & Decision Trees',
  },
  {
    title: 'Data Science',
    slug: 'data-science',
    shortTitle: 'Data Science',
    category: 'AI & Data Science',
    iconName: 'Sparkles',
    description: 'Pandas DataFrames, NumPy vector math, Matplotlib/Seaborn visualization, and exploratory data analysis (EDA).',
    lang: 'python',
    codeExt: 'eda.py',
    sampleCode1: `import pandas as pd\nimport numpy as np\n\ndf = pd.DataFrame({\n    'Name': ['Alice', 'Bob', 'Charlie'],\n    'Score': [85, 92, 78]\n})\nprint(df.describe())`,
    sampleCode2: `# GroupBy Aggregation in Pandas\ndf.groupby('Category')['Revenue'].agg(['mean', 'sum', 'count'])`,
    ch2Title: 'Pandas Data Cleaning & Exploratory Data Analysis (EDA)',
  },
];

export async function seedTutorialSubjectsAndChapters() {
  logger.info('==========================================');
  logger.info('Starting 55+ Subjects & Chapters Seeding in MongoDB...');
  logger.info('==========================================');

  const connected = await connectDB();
  if (!connected) {
    logger.error('Database connection failed. Aborting seeding.');
    process.exit(1);
  }

  try {
    let subjectsUpserted = 0;
    let chaptersCreated = 0;

    for (let i = 0; i < ALL_IT_SUBJECTS.length; i++) {
      const s = ALL_IT_SUBJECTS[i];

      // 1. Upsert Subject
      await TutorialSubject.findOneAndUpdate(
        { slug: s.slug },
        {
          title: s.title,
          slug: s.slug,
          shortTitle: s.shortTitle,
          category: s.category,
          iconName: s.iconName,
          description: s.description,
          order: i + 1,
          isPublished: true,
        },
        { upsert: true, new: true }
      );
      subjectsUpserted++;

      // 2. Ensure Chapter 1: Introduction to <Subject>
      const ch1Slug = `intro-${s.slug}`;
      const ch1Existing = await Tutorial.findOne({ slug: ch1Slug });
      if (!ch1Existing) {
        await Tutorial.create({
          title: `Introduction to ${s.title}`,
          slug: ch1Slug,
          track: s.slug,
          sectionTitle: 'Foundations & Basics',
          category: s.category,
          level: 'Beginner',
          readingTime: 5,
          excerpt: `An essential beginner guide to ${s.title}: what it is, why it matters in modern tech, and fundamental principles.`,
          quickFacts: `${s.title} is an industry-standard skill required across top engineering teams and technology workflows.`,
          keyPoints: [
            `Core definitions, purpose, and ecosystem of ${s.title}`,
            `Industry use-cases and why developers choose ${s.title}`,
            `Standard setup, terminology, and foundational code patterns`,
          ],
          diagramImageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1200&auto=format&fit=crop',
          content: `### 1. What is ${s.title}?
${s.title} is one of the most critical technologies in modern computer science and software development.

### 2. Why Learn ${s.title}?
- **Industry Standard**: Adopted by leading tech companies globally.
- **High Performance**: Optimized for scalable, secure, and production-ready applications.
- **Strong Community**: Extensive documentation, libraries, and tooling support.

### 3. Basic Code Example
Here is a practical starter example to understand how ${s.title} works in practice:

\`\`\`${s.lang}
${s.sampleCode1}
\`\`\`

### 4. Summary & Next Steps
Mastering the foundations of ${s.title} prepares you for advanced architectural concepts, performance tuning, and enterprise applications.`,
          codeSnippet: {
            language: s.lang,
            filename: s.codeExt,
            code: s.sampleCode1,
            output: 'Executed successfully with 0 errors.',
          },
          quiz: {
            question: `What is the primary role of ${s.title} in modern computer science?`,
            options: [
              `Provides essential foundations and production workflows for ${s.category}`,
              'Deprecated legacy tool with no industry adoption',
              'Only used for hardware fabrication',
              'None of the above',
            ],
            correctIndex: 0,
            explanation: `${s.title} is a cornerstone of modern software engineering in ${s.category}.`,
          },
          isPublished: true,
          publishedAt: new Date(),
        });
        chaptersCreated++;
      }

      // 3. Ensure Chapter 2: Core Architecture & Concepts
      const ch2Slug = `core-concepts-${s.slug}`;
      const ch2Existing = await Tutorial.findOne({ slug: ch2Slug });
      if (!ch2Existing) {
        await Tutorial.create({
          title: `${s.title} — ${s.ch2Title}`,
          slug: ch2Slug,
          track: s.slug,
          sectionTitle: 'Core Architecture',
          category: s.category,
          level: 'Intermediate',
          readingTime: 8,
          excerpt: `Technical deep-dive into internal execution mechanisms, data flows, and architectural design patterns of ${s.title}.`,
          quickFacts: `Understanding internal architecture and execution guarantees in ${s.title} enables developers to write robust and scalable software.`,
          keyPoints: [
            `Under-the-hood execution pipeline and lifecycle in ${s.title}`,
            `Performance optimization and resource management patterns`,
            `Enterprise architecture best practices and common anti-patterns`,
          ],
          diagramImageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
          content: `### 1. Internal Architecture & Mechanics
In this chapter, we explore how ${s.title} executes under the hood, how resources are allocated, and how data flows through the system.

### 2. Core Architectural Patterns
- **Separation of Concerns**: Modular components ensure testability and maintainability.
- **Resource Management**: Efficient memory layout and minimal latency overhead.
- **Scalability**: Designed to handle production concurrency and enterprise workloads.

### 3. Implementation Code
Here is an architectural implementation demonstrating best practices in ${s.title}:

\`\`\`${s.lang}
${s.sampleCode2}
\`\`\`

### 4. Enterprise Best Practices
Always structure your codebase with clear boundaries, enforce automated testing, and monitor execution bottlenecks in production.`,
          codeSnippet: {
            language: s.lang,
            filename: s.codeExt,
            code: s.sampleCode2,
            output: 'Architecture validated and compiled cleanly.',
          },
          quiz: {
            question: `Why is understanding the internal architecture of ${s.title} critical for senior engineers?`,
            options: [
              'It enables writing optimized, scalable code and preventing memory/performance bottlenecks',
              'It allows bypassing security restrictions',
              'It eliminates the need for testing',
              'Internal architecture is irrelevant in software development',
            ],
            correctIndex: 0,
            explanation: 'Knowing how a system executes under the hood allows engineers to write scalable, high-performance code.',
          },
          isPublished: true,
          publishedAt: new Date(),
        });
        chaptersCreated++;
      }
    }

    logger.info(`✅ Successfully seeded/updated ${subjectsUpserted} IT Subjects!`);
    logger.info(`✅ Successfully created ${chaptersCreated} chapters in MongoDB!`);

    await disconnectDB();
    process.exit(0);
  } catch (err: any) {
    logger.error('Error during tutorial seeding:', err);
    await disconnectDB();
    process.exit(1);
  }
}

if (require.main === module) {
  seedTutorialSubjectsAndChapters();
}
